stasher:
  address: "0.0.0.0"
  port: "8080"
  salt: "longAndSecureSalt"
  hostname: "127.0.0.1:8081"
  scheme: "http"
couchdb:
  protocol: "https"
  address: "db"
  port: "6984"
  dbname: "stasher"
  username: "stasher"
  password: "stasher"
  cert_check: false
